name: Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deps
        run: sudo apt -y update && sudo apt -y install cmake build-essential

      - name: Clean all
        run: ./clean_all.sh

      - name: Build all
        run: ./build_all.sh build
